// Microcopy library — all user-facing strings live here.
// Liquidation copy is matter-of-fact, never apologetic.
// No exclamation marks. No emoji.

export const copy = {
  brand: {
    name: "Collat",
    tagline: "Bank on Bitcoin.",
    heroLine1: "Spend your Bitcoin",
    heroLine2: "without selling it.",
    heroSub: "Collat auto-borrows the exact MUSD needed at checkout, settles the merchant instantly, and lets you repay on your own schedule.",
  },

  nav: {
    product: "Product",
    card: "Card",
    ai: "AI",
    docs: "Docs",
    connect: "Connect Wallet",
    dashboard: "Dashboard",
    history: "History",
    settings: "Settings",
  },

  wallet: {
    connectTitle: "Connect to Collat",
    connectSub: "Choose how you want to connect to Mezo Testnet.",
    passport: "Mezo Passport",
    passportDesc: "The native Mezo smart wallet.",
    metamask: "MetaMask",
    metamaskDesc: "Any EIP-1193 browser wallet.",
    safe: "Safe Multisig",
    safeDesc: "Team or DAO multi-signature wallet.",
    connected: "Connected",
    disconnect: "Disconnect",
    wrongNetwork: "Wrong Network",
    switchNetwork: "Switch to Mezo Testnet",
    networkGuardTitle: "Mezo Testnet required",
    networkGuardSub: "Collat runs on Mezo Testnet. Please switch networks to continue.",
  },

  dashboard: {
    title: "Your Position",
    btcDeposited: "BTC Deposited",
    musdBorrowed: "MUSD Borrowed",
    availableToBorrow: "Available to Borrow",
    liquidationPrice: "Liquidation Price",
    ltv: "LTV",
    depositBtc: "Deposit BTC",
    withdraw: "Withdraw",
    borrowMusd: "Borrow MUSD",
    repay: "Repay",
    recentActivity: "Recent Activity",
    viewAll: "View all",
    emptyTitle: "Deposit your first BTC",
    emptyAssurances: ["On-chain", "Self-custody", "No KYC"],
    emptyExplainer: "Deposit BTC as collateral. Collat auto-borrows MUSD at checkout. Your BTC stays in the vault — you keep the upside. The loan-to-value (LTV) cap is 60%; positions above 75% LTV are subject to liquidation with a 5% penalty.",
  },

  borrow: {
    title: "Borrow MUSD",
    amountLabel: "Amount to borrow",
    amountPlaceholder: "0.00",
    sliderLabel: "Borrow amount",
    quickChips: ["25%", "50%", "MAX"],
    previewTitle: "Position preview",
    currentLtv: "Current LTV",
    newLtv: "New LTV",
    currentHealth: "Health",
    newHealth: "New Health",
    liqPriceBefore: "Liquidation price",
    liqPriceAfter: "New liquidation price",
    riskTitle: "Liquidation risk",
    riskBody: "If BTC drops enough to push your LTV above 75%, any address can liquidate your position. They repay your debt and receive the equivalent BTC plus a 5% penalty. The remaining collateral stays in your vault.",
    reviewBtn: "Review",
    confirmBtn: "Confirm in wallet",
    successTitle: "Borrow confirmed",
    maxLtvError: (excess: string) => `Exceeds 60% max LTV — reduce by ${excess} MUSD`,
  },

  repay: {
    title: "Repay MUSD",
    amountLabel: "Amount to repay",
    fullRepayBtn: "MAX — full repay",
    confirmBtn: "Confirm in wallet",
    successTitle: "Repay confirmed",
    fullRepaySuccess: "Position fully repaid. BTC available to withdraw.",
    openDashboard: "Open Dashboard",
  },

  deposit: {
    title: "Deposit BTC",
    amountLabel: "Amount to deposit",
    confirmBtn: "Confirm in wallet",
    successTitle: "Deposit confirmed",
  },

  withdraw: {
    title: "Withdraw BTC",
    amountLabel: "Amount to withdraw",
    blockedByDebt: "Repay all MUSD before withdrawing collateral.",
    confirmBtn: "Confirm in wallet",
    successTitle: "Withdrawal confirmed",
  },

  txSimulation: {
    title: "Transaction preview",
    calldata: "Call",
    gasEstimate: "Estimated gas",
    balanceAfter: "Balance after",
    explorerLink: "View on Mezo Explorer",
  },

  history: {
    title: "Transaction history",
    exportCsv: "Export CSV",
    filterAll: "All",
    filterDeposit: "Deposits",
    filterBorrow: "Borrows",
    filterRepay: "Repays",
    filterLiquidate: "Liquidations",
    empty: "No transactions yet.",
  },

  card: {
    title: "Collat Card",
    tagline: "Tap. Sign. Done.",
    orderBtn: "Order a Collat Card",
    activateBtn: "Activate a card",
    statusPaired: "Card paired",
    statusNotPaired: "No card paired",
    feature1Title: "Self-custody",
    feature1Body: "Your private key lives inside the card chip. No custodian, no seed phrase, no account.",
    feature2Title: "EAL6+ Chip",
    feature2Body: "Samsung-certified secure element. The key is generated on-chip and never leaves — ever.",
    feature3Title: "No seed phrase",
    feature3Body: "Link 2–3 cards during setup. Lose one? Recover from a backup card. Key never exists in readable form.",
  },

  cardActivate: {
    step1Title: "Pair your card",
    step1Body: "Tap your card to the back of your phone.",
    step1Simulate: "Simulate tap",
    step2Title: "Generating key",
    step2Body: "Your private key is being generated inside the card's EAL6+ secure chip. It will never leave the chip.",
    step3Title: "Backup",
    step3Body: "Link a second card to recover if you lose this one.",
    step3CTA: "Pair a backup card",
    step3Skip: "Skip backup",
    step3SkipWarning: "Skipping backup means this card is the only way to access your wallet. If you lose it, funds are unrecoverable.",
    doneTitle: "Card activated.",
    doneBody: "Your Collat Card is linked to your Mezo ID.",
    doneCTA: "Open Dashboard",
  },

  ai: {
    alertTitle: "BTC volatility elevated",
    alertBodyFn: (ltvPct: string, dropPct: string, addBtc: string) =>
      `Your position is healthy at ${ltvPct} LTV, but if BTC drops ${dropPct}, you would hit 60%. Consider adding ${addBtc} BTC.`,
    alertCTA: "Add collateral",
    smartLimitTitle: "Smart spend limit",
    smartLimitSub: "AI-adjusted daily limit based on volatility, repayment history, and MUSD liquidity.",
    smartLimitWhy: "Why?",
    taxReportTitle: "Tax report",
    chatTitle: "Ask Collat",
    chatPlaceholder: "How much can I spend today?",
    chatTyping: "Collat is thinking…",
  },

  errors: {
    ZeroAmount: "Amount must be greater than zero.",
    InsufficientCollateral: "Insufficient collateral balance.",
    OutstandingLoan: "Repay all MUSD before withdrawing collateral.",
    ExceedsMaxLTV: "Borrow amount exceeds the 60% maximum LTV.",
    OverRepay: "Repay amount exceeds current debt.",
    NotLiquidatable: "Position is not yet liquidatable.",
    generic: "Something went wrong. Please try again.",
  },

  checkout: {
    title: "Merchant checkout",
    cartItem1: "Espresso",
    cartItem1Price: "$4.50",
    cartItem2: "Hardback book",
    cartItem2Price: "$28.00",
    total: "Total",
    payWithCollat: "Pay with Collat",
    step1: "Reading position…",
    step2: "Constructing auto-borrow for $32.50…",
    step3: "Signing with wallet…",
    receiptTitle: "Payment complete",
    receiptLine1: "Merchant settled",
    receiptLine2: "Position updated",
    receiptDebt: "New debt",
  },

  settings: {
    title: "Settings",
    theme: "Theme",
    themeDark: "Dark",
    themeLight: "Light",
    themeSystem: "System",
    resetTitle: "Reset demo state",
    resetBody: "This clears all mock position data and transaction history from localStorage. Your connection and theme preference are preserved.",
    resetBtn: "Reset demo state",
    resetConfirm: "Reset confirmed. Position cleared to zero.",
  },
} as const;
